# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetMedoid <- function(distanceValues) {
    .Call(`_distops_GetMedoid`, distanceValues)
}

GetMedoids <- function(distanceValues, groupingValues) {
    .Call(`_distops_GetMedoids`, distanceValues, groupingValues)
}

DiagonalSubsetter <- function(x, indices) {
    .Call(`_distops_DiagonalSubsetter`, x, indices)
}

OffDiagonalSubsetter <- function(x, row_indices, col_indices) {
    .Call(`_distops_OffDiagonalSubsetter`, x, row_indices, col_indices)
}

