#' Distance Matrix Subset Operator
#'
#' @description Subset operator for the distance matrix stored as an object of
#'   class [`stats::dist`].
#'
#' @param x An object of class [`stats::dist`].
#' @param i An integer vector of row indices. Values must be either all positive
#'   in which case they indicate the rows to select, or all negative in which
#'   case they indicate the rows to omit.
#' @param j An integer vector of column indices. Values must be either all
#'   positive in which case they indicate the columns to select, or all negative
#'   in which case they indicate the columns to omit.
#' @param drop A logical value indicating whether the result should be coerced
#'   to a vector or matrix if possible.
#' @param ... Additional arguments passed to `[.dist`.
#'
#' @return A numeric matrix storing the pairwise distances between the requested
#'   observations.
#' @export
#'
#' @examples
#' D <- stats::dist(iris[, 1:4])
#' D[2:3, 7:12]
"[.dist" <- function(x, i, j, drop = TRUE, ...) {
  if (missing(i) && missing(j)) {
    return(x)
  }

  N <- attr(x, "Size")
  row_ids <- attr(x, "Labels")
  if (length(row_ids) == 0) {
    row_ids <- 1:N
  }

  if (missing(i)) {
    i <- seq_len(N)
  }

  if (missing(j)) {
    j <- seq_len(N)
  }

  if (is.numeric(i)) {
    i <- as.integer(i)
  }

  if (is.numeric(j)) {
    j <- as.integer(j)
  }

  if (is.null(i)) {
    i <- seq_len(N)
  }

  if (is.null(j)) {
    j <- seq_len(N)
  }

  if (any(i < 0)) {
    if (!all(i < 0)) {
      cli::cli_abort("The row indices must be all non-negative or all negative.")
    }
    i <- seq_len(N)[i]
  }

  if (any(j < 0)) {
    if (!all(j < 0)) {
      cli::cli_abort("The column indices must be all non-negative or all negative.")
    }
    j <- seq_len(N)[j]
  }

  if (any(i < 1L) || any(i > N)) {
    cli::cli_abort("The row indices must be all between 1 and {.arg N}.")
  }

  if (any(j < 1L) || any(j > N)) {
    cli::cli_abort("The column indices must be all between 1 and {.arg N}.")
  }

  common_indices <- intersect(i, j)
  i_diff <- setdiff(i, common_indices)
  j_diff <- setdiff(j, common_indices)

  nc <- length(common_indices)
  D <- numeric(length = nc * (nc - 1) / 2)
  class(D) <- "dist"
  if (nc > 0) {
    D <- DiagonalSubsetter(x, common_indices)
    attributes(D) <- attributes(x)
    attr(D, "Labels") <- row_ids[common_indices]
    attr(D, "Size") <- length(common_indices)
  }

  R <- matrix(nrow = length(i_diff), ncol = length(j))
  if (length(i_diff) > 0) {
    R <- OffDiagonalSubsetter(x, i_diff, j)
    rownames(R) <- row_ids[i_diff]
  }
  colnames(R) <- row_ids[j]

  C <- matrix(nrow = length(i), ncol = length(j_diff))
  if (length(j_diff) > 0) {
    C <- OffDiagonalSubsetter(x, i, j_diff)
    colnames(C) <- row_ids[j_diff]
  }
  rownames(C) <- row_ids[i]

  out <- list(D = D, R = R, C = C)
  class(out) <- "subdist"
  out
}


#' Coerce a `subdist` object to a matrix
#'
#' @description Coerce a `subdist` object to a matrix.
#'
#' @param x An object of class `subdist` as generated by [`[.dist`].
#' @param ... Additional arguments passed to [`as.matrix`]. Currently ignored.
#'
#' @return A numeric matrix storing the pairwise distances between the requested
#'   observations.
#' @export
#'
#' @examples
#' D <- stats::dist(iris[, 1:4])
#' x <- D[1:3, 2:7]
#' as.matrix(x)
as.matrix.subdist <- function(x, ...) {
  out <- matrix(0, nrow = nrow(x$C), ncol = ncol(x$R))
  rownames(out) <- rownames(x$C)
  colnames(out) <- colnames(x$R)
  D <- as.matrix(x$D)
  out[rownames(out) %in% rownames(D), colnames(out) %in% colnames(D)] <- D
  out[rownames(out) %in% rownames(x$C), !(colnames(out) %in% colnames(D))] <- x$C
  out[!(rownames(out) %in% rownames(D)), colnames(out) %in% colnames(x$R)] <- x$R
  out
}
